name: Cypress Demo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to test'
        required: true
        default: 'stage'
      deployment:
        description: 'Auto Deployment'
        required: true
        default: 'no'
  #Infinite cycle for some reason
  #deployment_status:
  #  state:
  #    types: ["success"]
jobs:
  cypress-github-pipeline:
    runs-on: ubuntu-latest
    env:
      #${{ github.event_name == 'workflow_dispatch' }}
      TEST_ENVIRONMENT: ${{ github.event.inputs.deployment == 'yes' && 'dev' || github.event.inputs.env}}
    environment: "$TEST_ENVIRONMENT"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repo Checkout
        uses: actions/checkout@v2
      
      #Random echos
      - name: Echoing envinronment under test
        run: |
          echo "Running in $TEST_ENVIRONMENT"
          echo test, and deploy your project

      #NPM Installation 
      - name: Cypress Execution
        uses: cypress-io/github-action@v2.9.7
        with:
          record: true
          browser: chrome
          headless: true
        env:
          CYPRESS_gitHubMsg: ${{ secrets.GIT_CUSTOM_MSG }} running in $TEST_ENVIRONMENT
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_DASHBOARD_ID }}
