name: Cypress Pipeline

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to test'
        required: true
        default: 'dev'
      
      #Workaround while understanding deployment_status
      deployment:
        description: 'Auto Deployment'
        required: true
        default: 'no'

jobs:
  cypress-github-pipeline:
    runs-on: macos-11
    environment: ${{ inputs.env }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repo Checkout
        uses: actions/checkout@v3
      
      # Setting environment
      - name: Set Up Environment
        run: |
          echo "TEST_ENVIRONMENT=${{ github.event.inputs.deployment == 'yes' && 'dev' || github.event.inputs.env}}" >> $GITHUB_ENV
          mkdir cypress/config/cucumber_json
          echo "${{ github.workspace }}/cypress/config/cucumber_json" >> $GITHUB_PATH
          cd cypress/config/cucumber_json
          curl https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-darwin-amd64 -o cucumber-json-formatter
          chmod +x cucumber-json-formatter
          echo "USER_$(echo ${{ inputs.env }} | tr '[:lower:]' '[:upper:]')=${{ secrets.CYPRESS_USERNAME }}" >> $GITHUB_ENV
          echo "PASS_$(echo ${{ inputs.env }} | tr '[:lower:]' '[:upper:]')=${{ secrets.CYPRESS_PASSWORD }}" >> $GITHUB_ENV
      
      # chmod +x .github/scripts/github-secrets.sh
      # - name: Secrets Shell
      #  run: |
      #    echo '${{ toJSON(secrets) }}' | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> .env
      #    .github/scripts/github-secrets.sh ${{ inputs.env }}

      # Run Test and Deploy
      - name: Quality Gates
        run: |
          echo ${{ github.actor }} : ${{ github.triggering_actor }} : ${{ github.action_ref }} : 
          echo ${{ github.repository }} : ${{ github.sha }}
          echo ${{ github.event_path }} : ${{ github.sha }}
          echo "CLOUD_MSG=$(echo Cypress Automation `git log --pretty=oneline --format='%C(auto) %h %s' | head -n 1`)" >> $GITHUB_ENV
          echo Running in ${{ env.TEST_ENVIRONMENT }}
          echo $(env)
          echo "TRIGGER_AUTOMATION=true" >> $GITHUB_ENV
          echo Test, and deploy your project

      #NPM Installation and Cypress execution
      - name: Cypress Execution
        if: ${{( inputs.env == 'dev' || env.TRIGGER_AUTOMATION ==  true )}}
        uses: cypress-io/github-action@v4
        with:
          ci-build-id: '${{ github.job }}:${{ github.run_number }}-${{ github.run_attempt }}'
          tag: '${{ github.job }}:${{ github.run_number }}-${{ github.run_attempt }}'
          record: true
          browser: chrome
          headed: false
          install: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_DASHBOARD_ID }}
          CYPRESS_TEST_TRIGGER: ${{github.event_name}}
          CYPRESS_envKey: ${{env.TEST_ENVIRONMENT}}
          CYPRESS_TAGS: "not @skip"
          CYPRESS_ACTION_TEST: ${{ secrets.CYPRESS_ACTION_TEST }}
          CYPRESS_username: ${{ env.USER_DEV }}
          CYPRESS_password: ${{ env.PASS_DEV }}
          COMMIT_INFO_MESSAGE: ${{ env.CLOUD_MSG }}
          COMMIT_INFO_SHA: ${{github.event.pull_request.head.sha}}
      
      # - name: Check Reports Outputs
      #   run: |
      #     echo 'JSON_REPORT<<EOF' >> $GITHUB_ENV
      #     cat 'cypress/results/reports/cucumber_json/cucumber-messages.ndjson' | cucumber-json-formatter > cucumber-results.json >> $GITHUB_ENV
      #     echo 'EOF' >> $GITHUB_ENV
      #     cat cucumber-results.json
      
      - name: Check Reports Outputs
        if: always()
        run: |
          cat 'cypress/results/reports/cucumber_json/cucumber-messages.ndjson' | cucumber-json-formatter > cucumber-results.json
          cat cucumber-results.json

