name: Cypress Pipeline

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to test'
        required: true
        default: 'dev'
      
      #Workaround while understanding deployment_status
      deployment:
        description: 'Auto Deployment'
        required: true
        default: 'no'
  #Infinite cycle for some reason
  #deployment_status:
  #  state:
  #    types: ["success"]

jobs:
  cypress-github-pipeline:
    runs-on: ubuntu-latest
    # env:
      #${{ github.event_name == 'workflow_dispatch' }}
      # TEST_ENVIRONMENT: ${{ github.event.inputs.deployment == 'yes' && 'dev' || github.event.inputs.env}}
    # environment: "$TEST_ENVIRONMENT"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repo Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # Setting environment
      - name: Set Up Environment
        run: |
          echo "TEST_ENVIRONMENT=${{ github.event.inputs.deployment == 'yes' && 'dev' || github.event.inputs.env}}" >> $GITHUB_ENV
          curl https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-linux-amd64 -o cypress/config/cucumber_json/cucumber-json-formatter
          chmod +x cypress/config/cucumber_json/cucumber-json-formatter
          echo "${{ github.workspace }}/cypress/config/cucumber_json" >> $GITHUB_PATH
          cd cypress/config/cucumber_json && ls -al

      # Run Test and Deploy
      - name: Quality Gates
        run: |
          echo $PATH
          echo Running in ${{ env.TEST_ENVIRONMENT }}
          echo Test, and deploy your project
          cucumber-json-formatter --help

      #NPM Installation 
      - name: Cypress Execution
        uses: cypress-io/github-action@v4
        with:
          ci-build-id: '${{ github.job }}:${{ github.run_number }}-${{ github.run_attempt }}'
          tag: '${{ github.job }}:${{ github.run_number }}-${{ github.run_attempt }}'
          record: true
          browser: chrome
          headed: false
          install: true
        env:
          CYPRESS_TAGS: "not @skip"
          CYPRESS_TEST_TRIGGER: ${{github.event_name}}
          CYPRESS_envKey: ${{env.TEST_ENVIRONMENT}}
          CYPRESS_gitHubMsg: ${{ secrets.GIT_CUSTOM_MSG }} running in ${{env.TEST_ENVIRONMENT}}
          CYPRESS_ACTION_TEST: ${{ secrets.CYPRESS_ACTION_TEST }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_DASHBOARD_ID }}
