name: Cypress Demo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to test'
        required: true
        default: 'stage'
      deployment:
        description: 'Auto Deployment'
        required: true
        default: 'no'
  deployment_status:
    state:
      types: ["success"]
jobs:
  # Name of the JOB
  cypress-github-pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #if: ${{ github.event_name == 'workflow_dispatch' }}
    if: ${{ github.event.inputs.deployment == 'yes' }}
    environment: ${{ (github.event.inputs.deployment == 'yes' && 'dev') || 'github.event.inputs.env'}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repo Checkout
        uses: actions/checkout@v2
      
      #Random echos
      - name: Echoing envinronment under test
        run: |
          echo "Running in ${{ github.event.inputs.env }}"
          echo test, and deploy your project

      #NPM Installation 
      - name: Cypress Execution
        uses: cypress-io/github-action@v2.9.7
        with:
          record: true
          browser: chrome
          headless: true
        env:
          CYPRESS_gitHubMsg: ${{ secrets.GIT_CUSTOM_MSG }} running in ${{ github.event.inputs.env }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_DASHBOARD_ID }}
